--Dirty read T1
INSERT INTO Series
	(id,seasons,nr_of_episodes,name)
VALUES
	(1,5,108,'Dynasty'),
	(2,2,20,'Outer Banks')
SELECT * FROM Series


BEGIN TRANSACTION
UPDATE Series SET seasons=10
WHERE id = 2
WAITFOR DELAY '00:00:10'
ROLLBACK TRANSACTION

SELECT * FROM LogChanges

--Dirty read T2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED --solution
BEGIN TRANSACTION
SELECT * FROM Series
WAITFOR DELAY '00:00:15'
SELECT * FROM Series
COMMIT TRAN