--Phantom read T1
BEGIN TRAN
WAITFOR DELAY '00:00:04'
INSERT INTO Series(id,seasons,nr_of_episodes,name)
VALUES (6, 10,11,'Lucifer')
COMMIT TRAN

BEGIN TRAN
WAITFOR DELAY '00:00:05'
INSERT INTO Series(id,seasons,nr_of_episodes,name)
VALUES (7, 3,50,'Outer Banks')
COMMIT TRAN

SELECT * FROM Series



--Phantom read T2

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- solution
BEGIN TRAN
SELECT * FROM Series
WAITFOR DELAY '00:00:05'
SELECT * FROM Series
COMMIT TRAN

--DELETE FROM Series WHERE id = 7

