# Generated by Django 4.1.7 on 2023-03-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_citybreaks_city_alter_citybreaks_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('transport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CityBreakPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractDate', models.DateField(auto_now_add=True)),
                ('cityBreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.citybreak')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('nrOfEmployees', models.IntegerField()),
                ('nrOfOffers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CityBreaks',
        ),
        migrations.AddField(
            model_name='citybreakperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.person'),
        ),
    ]
