# Generated by Django 4.1.7 on 2023-03-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_remove_citybreak_agency_person_citybreak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cityBreak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.citybreak'),
        ),
        migrations.CreateModel(
            name='CityBreakAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatingDate', models.DateField()),
                ('enrollmentDeadline', models.DateField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.travelagency')),
                ('cityBreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.citybreak')),
            ],
        ),
        migrations.AddField(
            model_name='citybreak',
            name='persons',
            field=models.ManyToManyField(through='snippets.CityBreakAgency', to='snippets.travelagency'),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='cityBreaks',
            field=models.ManyToManyField(through='snippets.CityBreakAgency', to='snippets.citybreak'),
        ),
    ]
