# Generated by Django 4.1.7 on 2023-03-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_person_citybreak_citybreakagency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citybreak',
            old_name='persons',
            new_name='agencies',
        ),
    ]
