# Generated by Django 4.1.7 on 2023-03-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_rename_persons_citybreak_agencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citybreak',
            old_name='agencies',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='travelagency',
            old_name='cityBreaks',
            new_name='cityBreak',
        ),
    ]
