# Generated by Django 4.1.7 on 2023-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citybreaks',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citybreaks',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citybreaks',
            name='hotel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citybreaks',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citybreaks',
            name='transport',
            field=models.CharField(max_length=100),
        ),
    ]
