# Generated by Django 4.1.7 on 2023-03-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_citybreakperson_advancepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citybreak',
            name='agency',
        ),
        migrations.AddField(
            model_name='person',
            name='cityBreak',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.citybreak'),
        ),
        migrations.DeleteModel(
            name='CityBreakPerson',
        ),
    ]
